stages:
  - build
  - test
  - deploy
  - sonar

image: gradle:7.3.3-jdk17

build:
  stage: build
  script:
    - gradle assemble --parallel

test:
  stage: test
  script:
    - gradle check --parallel
    - gradle jacocoTestReport --parallel
    - gradle jacocoTestCoverageVerification
  artifacts:
    paths:
      - build/jacoco/allTestCoverage.exec

deploy:
  stage: deploy
  script:
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api_key=$HEROKU_API_KEY
  only:
    - master

sonarCheck:
  stage: sonar
  needs:
    - build
  script:
    - gradle sonarqube -Dsonar.login=$SONAR_TOKEN
  only:
    - master